import {useState} from 'react'
import {useNavigate} from 'react-router-dom'
import {preview} from '../assets'
import { getRandomPrompt } from '../utils'
import FormField from '../components/FormField'
import Loader from '../components/Loader'

const CreatePost = () => {

  const navigate = useNavigate()
  const [form, setForm] = useState({
    name:'',
    prompt:'',
    photo:''
  })
  const [generateImg, setGenerateImg] = useState(false)
  const [loading, setLoading] = useState(false)

  const handleSubmit = () =>{

  }

  const handleChange = (e) => {
    setForm({...form, [e.target.value] : e.target.value})
  }

  const handleSurpriseMe = () => {
    const randomPrompt = getRandomPrompt(form.prompt)
    setForm({...form, prompt:randomPrompt})
  }

  const generateImage = () => {

  }

  return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>
          Create New Images
        </h1>
        <p className='mt-2 text-[#666e75] text-[14px] max-w-[500px]'>Create imaginative and visually stuning images generated by DALLE AI</p>
      </div>

      <form className='mt-16 max-w-3xl' onSubmit={handleSubmit}>
        <div className='flex flex-col gap-5'>
          <FormField
            labelName = "Your Name"
            type = "text"
            name="name"
            placeholder = "John Doe"
            value={form.name}
            handleChange={handleChange}
          />
          <FormField
            labelName = "Prompt"
            type = "text"
            name="prompt"
            placeholder = "a sea otter with a pearl earring by Johannes Vermeer"
            value={form.prompt}
            handleChange={handleChange}
            isSurpriseMe
            handleSurpriseMe={handleSurpriseMe}
          />
      <div 
        className='relative bg-gray-100 border border-gray-400 text-gray-900 text-sm rounded-lg focus:ring-[#6469ff] focus:border-[#4649ff] w-64 p-3 h-64 flex justify-center items-center mt-2'
        >
        {form.photo ? (
          <img 
          src={form.photo} 
          alt={form.prompt} 
          className='w-full h-full object-contain'
          />
          ) : (
            <img 
            src={preview} 
            alt={preview} 
            className='w-9/12 h-9/12 object-contain'
            />
            )}

        {generateImg && (
          <div className='absolute inset-0 z-0 flex justify-center items-center rounded-lg bg-[rgba(0,0,0,0.5)]'>
            <Loader/>
          </div>
        )}
      </div>
      </div>
      <div className='mt-5 flex gap-5'>
          <button
            type='button'
            onClick={generateImage}
            className='text-white bg-green-700 font-medium rounded-md text-sm w-full sm:w-auto px-5 py-2 text-center hover:bg-green-600 hover:scale-105 transition-all'
          >
            {generateImg ? "Generating..." : "Generate"}
          </button>
      </div>
    </form>
    </section>
  )
}

export default CreatePost