import {useState} from 'react'
import {useNavigate} from 'react-router-dom'
import {preview} from '../assets'
import { getRandomPrompt } from '../utils'
import FormField from '../components/FormField'
import Loader from '../components/Loader'

const CreatePost = () => {

  const navigate = useNavigate()
  const [form, setForm] = useState({
    name:'',
    prompt:'',
    photo:''
  })
  const [generateImg, setGenerateImg] = useState(false)
  const [loading, setLoading] = useState(false)

  const handleSubmit = () =>{

  }

  const handleChange = (e) => {

  }

  const handleSurpriseMe = () => {
    
  }

  return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>
          Create New Images
        </h1>
        <p className='mt-2 text-[#666e75] text-[14px] max-w-[500px]'>Create imaginative and visually stuning images generated by DALLE AI</p>
      </div>

      <form className='mt-16 max-w-3xl' onSubmit={handleSubmit}>
        <div className='flex flex-col gap-5'>
          <FormField
            labelName = "Your Name"
            type = "text"
            name="name"
            placeholder = "John Doe"
            value={form.name}
            handleChange={handleChange}
          />
          <FormField
            labelName = "Prompt"
            type = "text"
            name="prompt"
            placeholder = "a sea otter with a pearl earring by Johannes Vermeer"
            value={form.prompt}
            handleChange={handleChange}
            isSurpriseMe
            handleSurpriseMe={handleSurpriseMe}
          />
        </div>
      </form>

    </section>
  )
}

export default CreatePost